## Instalação do Pandera

In [38]:
pip install pandera

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandera in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (1.3.5)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (1.21.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.7/dist-packages (from pandera) (1.9.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (21.3)
Requirement already satisfied: typing-inspect>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (0.8.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from pandera) (4.1.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.7/dist-packages (from pandera) (1.14.1)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (from pandera) (6.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->pandera) (3.0.9)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->pandera) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->pandera) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.0->pandera) (1.15.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from typing-inspect>=0.6.0->pandera) (0.4.3)

##Instalação PySpark

In [39]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyspark in /usr/local/lib/python3.7/dist-packages (3.3.0)
Requirement already satisfied: py4j==0.10.9.5 in /usr/local/lib/python3.7/dist-packages (from pyspark) (0.10.9.5)

##IMPORTAÇÃO DAS BIBLIOTECAS PANDAS, PANDERA, PYSPARK E FERRAMENTAS

In [40]:
import pandas as pd
import pandera as pa

from pyspark.sql import SparkSession
from pyspark import SparkConf
import pyspark.sql.functions as F
from pyspark.sql.types import*

# Datasets

##Etanol Hidratado

In [221]:
# Carregamento do Dataframe Localmente

dfeh = pd.read_csv('/content/dataset_etanol_hidratado.csv',sep=',')

In [222]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',7500)

In [223]:
# Visão geral do dataset

dfeh

Output hidden; open in https://colab.research.google.com to view.

In [224]:
# Replace de etanol hidratado para Etanol Hidratado

dfeh['produto'] = dfeh['produto'].apply(lambda x: x.replace('etanol hidratado', 'Etanol Hidratado'))

In [225]:
# Convertendo as variãveis necessarias para string

dfeh['ano'] = dfeh['ano'].astype(str)

In [226]:
# Verificando os tipos das colunas

dfeh.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [227]:
# Backup

dfeh_pandas = dfeh.copy()

##Gasolina de Aviação

In [228]:
# Carregamento do Dataframe Localmente

dfga = pd.read_csv('/content/dataset_gasolina_aviacao.csv',sep=',')

In [229]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [230]:
# Visão geral do dataset

dfga

      ano_mês  uf              produto unid volume   criado_em  ano
0     2000-01  AC  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
1     2000-02  AC  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
2     2000-03  AC  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
3     2000-04  AC  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
4     2000-05  AC  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
...       ...  ..                  ...  ...    ...         ...  ...
7435  2022-08  AM  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
7436  2022-09  AM  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
7437  2022-10  AM  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
7438  2022-11  AM  Gasolina de Aviação   m3    NaN  2022-09-10  NaN
7439  2022-12  AM  Gasolina de Aviação   m3    NaN  2022-09-10  NaN

[7440 rows x 7 columns]

In [231]:
# Convertendo as variãveis necessarias para string

dfga['ano'] = dfga['ano'].astype(str)

In [232]:
# Verificando os tipos das colunas

dfga.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [233]:
# Backup

dfga_pandas = dfga.copy()

##Gasolina C

In [234]:
# Carregamento do Dataframe Localmente

dfgc = pd.read_csv('/content/dataset_gasolina_c.csv',sep=',')

In [235]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [236]:
# Replace de Gasolina_C para Gasolina C

dfgc['produto'] = dfgc['produto'].apply(lambda x: x.replace('Gasolina_C', 'Gasolina C'))

In [237]:
# Visão geral do dataset

dfgc

      ano_mês  uf     produto unid  volume   criado_em  ano
0     2000-01  AC  Gasolina C   m3   3.066  2022-09-10  NaN
1     2000-02  AC  Gasolina C   m3   3.495  2022-09-10  NaN
2     2000-03  AC  Gasolina C   m3   2.947  2022-09-10  NaN
3     2000-04  AC  Gasolina C   m3   3.024  2022-09-10  NaN
4     2000-05  AC  Gasolina C   m3   3.207  2022-09-10  NaN
...       ...  ..         ...  ...     ...         ...  ...
7447  2022-08  AM  Gasolina C   m3     NaN  2022-09-10  NaN
7448  2022-09  AM  Gasolina C   m3     NaN  2022-09-10  NaN
7449  2022-10  AM  Gasolina C   m3     NaN  2022-09-10  NaN
7450  2022-11  AM  Gasolina C   m3     NaN  2022-09-10  NaN
7451  2022-12  AM  Gasolina C   m3     NaN  2022-09-10  NaN

[7452 rows x 7 columns]

In [238]:
# Convertendo as variáveis necessárias para string

dfgc['volume'] = dfgc['volume'].astype(str)
dfgc['ano'] = dfgc['ano'].astype(str)

In [239]:
# Verificando os tipos das colunas

dfgc.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [240]:
# Backup

dfgc_pandas = dfgc.copy()

##GLP

In [241]:
# Carregamento do Dataframe Localmente

dfglp = pd.read_csv('/content/dataset_glp.csv',sep=',')

In [242]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [243]:
# Visão geral do dataset

dfglp

      ano_mês  uf produto unid  volume   criado_em  ano
0     2000-01  AC     GLP   m3   1.959  2022-09-10  NaN
1     2000-02  AC     GLP   m3   2.216  2022-09-10  NaN
2     2000-03  AC     GLP   m3   2.305  2022-09-10  NaN
3     2000-04  AC     GLP   m3   2.190  2022-09-10  NaN
4     2000-05  AC     GLP   m3   2.267  2022-09-10  NaN
...       ...  ..     ...  ...     ...         ...  ...
7435  2022-08  AM     GLP   m3     NaN  2022-09-10  NaN
7436  2022-09  AM     GLP   m3     NaN  2022-09-10  NaN
7437  2022-10  AM     GLP   m3     NaN  2022-09-10  NaN
7438  2022-11  AM     GLP   m3     NaN  2022-09-10  NaN
7439  2022-12  AM     GLP   m3     NaN  2022-09-10  NaN

[7440 rows x 7 columns]

In [244]:
# Convertendo as variaveis necessárias para string

dfglp['ano'] = dfglp['ano'].astype(str)
dfglp['volume'] = dfglp['volume'].astype(str)

In [245]:
# Verificando os tipos das colunas

dfglp.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [246]:
# Backup

dfglp_pandas = dfglp.copy()

##Óleo Combustível

In [247]:
# Carregamento do Dataframe Localmente

dfoc = pd.read_csv('/content/dataset_oleo_combustivel.csv',sep=',')

In [248]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [249]:
# Visão geral do dataset

dfoc

      ano_mês  uf           produto unid    volume   criado_em  ano
0     2003-01  AC  Óleo Combustível   m3    NaN     2022-09-10  NaN
1     2003-02  AC  Óleo Combustível   m3    NaN     2022-09-10  NaN
2     2003-03  AC  Óleo Combustível   m3      169   2022-09-10  NaN
3     2003-04  AC  Óleo Combustível   m3    NaN     2022-09-10  NaN
4     2003-05  AC  Óleo Combustível   m3    NaN     2022-09-10  NaN
...       ...  ..               ...  ...       ...         ...  ...
6859  2022-08  AM  Óleo Combustível   m3       NaN  2022-09-10  NaN
6860  2022-09  AM  Óleo Combustível   m3       NaN  2022-09-10  NaN
6861  2022-10  AM  Óleo Combustível   m3       NaN  2022-09-10  NaN
6862  2022-11  AM  Óleo Combustível   m3       NaN  2022-09-10  NaN
6863  2022-12  AM  Óleo Combustível   m3       NaN  2022-09-10  NaN

[6864 rows x 7 columns]

In [250]:
# Convertendo as variáveis necessárias para string

dfoc['ano'] = dfoc['ano'].astype(str)

In [251]:
# Verificando os tipos das colunas

dfoc.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [252]:
# Backup

dfoc_pandas = dfoc.copy()

##Óleo Diesel

In [253]:
# Carregamento do Dataframe Localmente

dfod = pd.read_csv('/content/dataset_oleo_diesel.csv',sep=',')

In [254]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [255]:
# Replace da coluna criado_em

dfod['criado_em'] = dfod['criado_em'].apply(lambda x: x.replace('2022-09-10', '2022-09-11'))

In [256]:
# Convertendo as variáveis necessárias para string

dfod['ano'] = dfod['ano'].astype(str)
dfod['volume'] = dfod['volume'].astype(str)

In [257]:
# Visão geral do dataset

dfod

      ano_mês  uf      produto unid  volume   criado_em  ano
0     2000-01  AC  Óleo Diesel   m3  18.025  2022-09-11  nan
1     2000-02  AC  Óleo Diesel   m3  18.336  2022-09-11  nan
2     2000-03  AC  Óleo Diesel   m3  16.654  2022-09-11  nan
3     2000-04  AC  Óleo Diesel   m3  15.146  2022-09-11  nan
4     2000-05  AC  Óleo Diesel   m3  18.681  2022-09-11  nan
...       ...  ..          ...  ...     ...         ...  ...
7447  2022-08  AM  Óleo Diesel   m3     nan  2022-09-11  nan
7448  2022-09  AM  Óleo Diesel   m3     nan  2022-09-11  nan
7449  2022-10  AM  Óleo Diesel   m3     nan  2022-09-11  nan
7450  2022-11  AM  Óleo Diesel   m3     nan  2022-09-11  nan
7451  2022-12  AM  Óleo Diesel   m3     nan  2022-09-11  nan

[7452 rows x 7 columns]

In [258]:
# Verificando os tipos das colunas

dfod.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [259]:
# Backup

dfod_pandas = dfod.copy()

##Querosene de Aviação

In [260]:
# Carregamento do Dataframe Localmente

dfqa = pd.read_csv('/content/dataset_querosene_aviacao.csv',sep=',')

In [261]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [262]:
# Visão geral do dataset

dfqa

      ano_mês  uf               produto unid   volume   criado_em  ano
0     2000-01  AC  Querosene de Aviação   m3    1.155  2022-09-10  NaN
1     2000-02  AC  Querosene de Aviação   m3    1.251  2022-09-10  NaN
2     2000-03  AC  Querosene de Aviação   m3  813.000  2022-09-10  NaN
3     2000-04  AC  Querosene de Aviação   m3  702.000  2022-09-10  NaN
4     2000-05  AC  Querosene de Aviação   m3  964.000  2022-09-10  NaN
...       ...  ..                   ...  ...      ...         ...  ...
7435  2022-08  AM  Querosene de Aviação   m3      NaN  2022-09-10  NaN
7436  2022-09  AM  Querosene de Aviação   m3      NaN  2022-09-10  NaN
7437  2022-10  AM  Querosene de Aviação   m3      NaN  2022-09-10  NaN
7438  2022-11  AM  Querosene de Aviação   m3      NaN  2022-09-10  NaN
7439  2022-12  AM  Querosene de Aviação   m3      NaN  2022-09-10  NaN

[7440 rows x 7 columns]

In [263]:
# Convertendo as variáveis necessárias para string

dfqa['ano'] = dfqa['ano'].astype(str)
dfqa['volume'] = dfqa['volume'].astype(str)

In [264]:
# Verificando os tipos das colunas

dfqa.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [265]:
# Backup

dfqa_pandas = dfqa.copy()

##Querosene Iluminante

In [266]:
# Carregamento do Dataframe Localmente

dfqi = pd.read_csv('/content/dataset_querosene_iluminante.csv',sep=',')

In [267]:
# Configurando a quantidade de linhas máximas mostradas em tela

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [268]:
# Replace da coluna criado_em

dfqi['criado_em'] = dfqi['criado_em'].apply(lambda x: x.replace('2022-09-10', '2022-09-11'))
dfqi['produto'] = dfqi['produto'].apply(lambda x: x.replace('Querosene_Iluminante', 'Querosene Iluminante'))

In [269]:
# Visão geral do dataset

dfqi

      ano_mês  uf               produto unid volume   criado_em  ano
0     2000-01  SP  Querosene Iluminante   m3    NaN  2022-09-11  NaN
1     2000-02  SP  Querosene Iluminante   m3    NaN  2022-09-11  NaN
2     2000-03  SP  Querosene Iluminante   m3    NaN  2022-09-11  NaN
3     2000-04  SP  Querosene Iluminante   m3    NaN  2022-09-11  NaN
4     2000-05  SP  Querosene Iluminante   m3    NaN  2022-09-11  NaN
...       ...  ..                   ...  ...    ...         ...  ...
4243  2022-08  BA  Querosene Iluminante   m3    NaN  2022-09-11  NaN
4244  2022-09  BA  Querosene Iluminante   m3    NaN  2022-09-11  NaN
4245  2022-10  BA  Querosene Iluminante   m3    NaN  2022-09-11  NaN
4246  2022-11  BA  Querosene Iluminante   m3    NaN  2022-09-11  NaN
4247  2022-12  BA  Querosene Iluminante   m3    NaN  2022-09-11  NaN

[4248 rows x 7 columns]

In [270]:
# Convertendo as variáveis necessárias para string

dfqi['ano'] = dfqi['ano'].astype(str)

In [271]:
# Verificando os tipos das colunas

dfqi.dtypes

ano_mês      object
uf           object
produto      object
unid         object
volume       object
criado_em    object
ano          object
dtype: object

In [272]:
# Backup

dfqi_pandas = dfqi.copy()

## CONCATENAÇÃO DE DATASETS

In [273]:
teste = pd.merge(dfeh_pandas, dfga_pandas, how = 'outer')

In [274]:
teste = pd.merge(teste, dfgc_pandas, how = 'outer')

In [275]:
teste = pd.merge(teste, dfglp_pandas, how = 'outer')

In [276]:
teste = pd.merge(teste, dfoc_pandas, how = 'outer')

In [277]:
teste = pd.merge(teste, dfod_pandas, how = 'outer')

In [278]:
teste = pd.merge(teste, dfqa_pandas, how = 'outer')

In [279]:
teste = pd.merge(teste, dfqi_pandas, how = 'outer')

In [280]:
# Arquivo foi salvo em formato csv sem o index

teste.to_csv('dataset_derivados_pandas.csv', index=False)

# Analise do Dataset Final e Tratamento com PySpark

In [281]:
# Carregamento do Dataframe Localmente

dfddpandas = pd.read_csv('/content/dataset_derivados_pandas.csv',sep=',')

In [282]:
# Análise dos dados da coluna volume
listavolume = []

for i in dfddpandas['volume']:
  listavolume.append(i)

In [283]:
listavolume

['501.0',
 '454.0',
 '676.0',
 '678.0',
 '1.467',
 '351.0',
 '451.0',
 '603.0',
 '531.0',
 '573.0',
 '305.0',
 '566.0',
 '431.0',
 '387.0',
 '428.0',
 '401.0',
 '427.0',
 '446.0',
 '402.0',
 '476.0',
 '427.0',
 '304.0',
 '365.0',
 '277.0',
 '310.0',
 '306.0',
 '395.0',
 '447.0',
 '411.0',
 '362.0',
 '379.0',
 '407.0',
 '458.0',
 '450.0',
 '288.0',
 '215.0',
 '250.0',
 '316.0',
 '350.0',
 '255.0',
 '253.0',
 '227.0',
 '376.0',
 '293.0',
 '373.0',
 '319.0',
 '294.0',
 '347.0',
 '297.0',
 '296.0',
 '282.0',
 '254.0',
 '337.0',
 '257.0',
 '338.0',
 '356.0',
 '332.0',
 '327.0',
 '318.0',
 '359.0',
 '303.0',
 '265.0',
 '260.0',
 '301.0',
 '312.0',
 '342.0',
 '311.0',
 '367.0',
 '361.0',
 '381.0',
 '342.0',
 '454.0',
 '344.0',
 '318.0',
 '293.0',
 '243.0',
 '286.0',
 '304.0',
 '357.0',
 '380.0',
 '378.0',
 '362.0',
 '407.0',
 '463.0',
 '448.0',
 '346.0',
 '404.0',
 '436.0',
 '474.0',
 '454.0',
 '596.0',
 '620.0',
 '620.0',
 '655.0',
 '683.0',
 '638.0',
 '687.0',
 '571.0',
 '647.0',
 '697.0',
 '763.0',
 '808.0',
 '880.0',
 '858.0',
 '835.0',
 '930.0',
 '858.0',
 '975.0',
 '907.0',
 '845.0',
 '957.0',
 '960.0',
 '968.0',
 '1.043',
 '1.056',
 '1.089',
 '1.095',
 '1.148',
 '963.0',
 '921.0',
 '802.0',
 '406.0',
 '517.0',
 '527.0',
 '503.0',
 '843.0',
 '776.0',
 '553.0',
 '1.201',
 '1.012',
 '1.093',
 '1.261',
 '1.011',
 '894.0',
 '881.0',
 '769.0',
 '967.0',
 '502.0',
 '1.026',
 '543.0',
 '479.0',
 '513.0',
 '470.0',
 '532.0',
 '453.0',
 '413.0',
 '493.0',
 '477.0',
 '514.0',
 '430.0',
 '448.0',
 '582.0',
 '520.0',
 '437.0',
 '468.0',
 '512.0',
 '448.0',
 '475.0',
 '477.0',
 '496.0',
 '523.0',
 '491.0',
 '521.0',
 '490.0',
 '469.0',
 '511.0',
 '505.0',
 '620.0',
 '575.0',
 '467.0',
 '43.0',
 '100.0',
 '353.0',
 '254.0',
 '318.0',
 '288.0',
 '295.0',
 '308.0',
 '335.0',
 '363.0',
 '408.0',
 '339.0',
 '496.0',
 '480.0',
 '458.0',
 '430.0',
 '475.0',
 '444.0',
 '575.0',
 '1.022',
 '1.062',
 '1.196',
 '799.0',
 '674.0',
 '621.0',
 '590.0',
 '473.0',
 '470.0',
 '463.0',
 '572.0',
 '710.0',
 '917.0',
 '640.0',
 '677.0',
 '672.0',
 '610.0',
 '625.0',
 '610.0',
 '625.0',
 '400.0',
 '315.0',
 '477.0',
 '502.0',
 '568.0',
 '619.0',
 '728.0',
 '618.0',
 '574.0',
 '651.0',
 '501.0',
 '544.0',
 '748.0',
 '690.0',
 '803.0',
 '912.0',
 '1.09',
 '787.0',
 '615.0',
 '545.0',
 '470.0',
 '558.0',
 '592.0',
 '730.0',
 '728.0',
 '742.0',
 '638.0',
 '658.0',
 '770.0',
 '676.0',
 '798.0',
 '663.0',
 '604.0',
 '525.0',
 '285.0',
 '210.0',
 '362.0',
 '485.0',
 '599.0',
 '791.0',
 '649.0',
 '610.0',
 '760.0',
 '682.0',
 '689.0',
 '784.0',
 '662.0',
 '663.0',
 '578.0',
 '504.0',
 '537.0',
 '477.0',
 '510.0',
 '460.0',
 '425.0',
 '375.0',
 '395.0',
 '556.0',
 '588.0',
 '593.0',
 '621.0',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '1.763',
 '1.803',
 '1.872',
 '2.04',
 '2.313',
 '2.028',
 '3.512',
 '3.396',
 '2.692',
 '1.837',
 '1.432',
 '1.506',
 '1.423',
 '1.664',
 '1.86',
 '1.588',
 '1.683',
 '1.481',
 '1.552',
 '1.403',
 '1.152',
 '1.36',
 '1.797',
 '1.95',
 '1.834',
 '1.332',
 '1.413',
 '1.353',
 '1.528',
 '1.313',
 '1.592',
 '1.895',
 '1.787',
 '2.032',
 '1.502',
 '1.46',
 '1.653',
 '1.436',
 '1.218',
 '1.957',
 '2.185',
 '2.078',
 '1.834',
 '1.345',
 '1.694',
 '1.355',
 '1.481',
 '1.814',
 '1.699',
 '1.295',
 '1.627',
 '1.563',
 '1.547',
 '2.168',
 '2.877',
 '2.532',
 '2.5',
 '2.146',
 '1.891',
 '1.673',
 '1.435',
 '1.37',
 '1.383',
 '1.37',
 '1.398',
 '2.063',
 '2.479',
 '2.913',
 '3.413',
 '3.159',
 '2.779',
 '3.136',
 '2.9',
 '2.501',
 '3.413',
 '2.693',
 '2.684',
 '2.824',
 '2.801',
 '3.199',
 '3.115',
 '2.952',
 '2.843',
 '2.978',
 '3.588',
 '2.918',
 '3.315',
 '3.329',
 '3.552',
 '4.028',
 '4.134',
 '4.591',
 '4.578',
 '5.26',
 '5.857',
 '6.311',
 '6.576',
 '5.878',
 '6.179',
 '6.78',
 '7.149',
 '7.183',
 '7.85',
 '6.343',
 '6.822',
 '7.249',
 '6.776',
 '8.318',
 '8.152',
 '7.211',
 '8.1',
 '8.27',
 '8.512',
 '8.752',
 '9.841',
 '8.797',
 '9.364',
 '9.764',
 '8.365',
 '9.388',
 '7.438',
 '4.408',
 '4.77',
 '5.85',
 '6.041',
 '6.092',
 '6.397',
 '6.596',
 '6.651',
 '6.691',
 '6.667',
 '8.502',
 '7.283',
 '6.68',
 '6.708',
 '3.678',
 '3.895',
 '3.922',
 '3.44',
 '3.433',
 '3.323',
 '3.276',
 '3.411',
 '4.189',
 '3.766',
 '3.485',
 '3.844',
 '3.521',
 '3.273',
 '3.074',
 '2.875',
 '3.073',
 '2.929',
 '3.203',
 '3.231',
 '3.282',
 '3.383',
 '3.481',
 '3.23',
 '2.957',
 '2.825',
 '2.62',
 '2.625',
 '2.489',
 '2.592',
 '2.769',
 '2.759',
 '3.238',
 '3.775',
 '3.16',
 '2.871',
 '2.785',
 '2.761',
 '2.48',
 '2.449',
 '2.934',
 '2.649',
 '2.767',
 '3.137',
 '3.892',
 '4.091',
 '4.847',
 '4.949',
 '5.235',
 '4.515',
 '4.526',
 '5.247',
 '4.767',
 '4.261',
 '6.239',
 '4.916',
 '5.116',
 '4.19',
 '2.518',
 '2.462',
 '2.294',
 '2.773',
 '2.78',
 '2.221',
 '2.543',
 '2.443',
 '2.566',
 '2.408',
 '2.567',
 '2.281',
 '2.339',
 '2.779',
 '2.355',
 '2.6',
 '2.263',
 '2.027',
 '2.78',
 '3.751',
 '2.857',
 '4.148',
 '4.88',
 '5.725',
 '5.109',
 '4.518',
 '3.334',
 '2.986',
 '4.9',
 '4.882',
 '5.504',
 '7.629',
 '10.538',
 '10.681',
 '11.769',
 '9.792',
 '7.616',
 '7.213',
 '6.378',
 '4.685',
 '3.895',
 '4.281',
 '3.945',
 '4.455',
 '5.162',
 '6.423',
 '9.763',
 '8.744',
 '6.712',
 '4.805',
 '2.707',
 '2.591',
 '3.449',
 '4.545',
 '5.077',
 '5.853',
 '6.22',
 '6.499',
 '7.723',
 '7.484',
 '8.409',
 '8.559',
 '7.681',
 '5.697',
 '4.351',
 '4.51',
 '4.18',
 '3.577',
 '4.453',
 '5.91',
 '6.775',
 '5.891',
 '5.354',
 '11.82',
 '8.227',
 '7.837',
 '6.014',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '119.0',
 '164.0',
 '108.0',
 '124.0',
 '124.0',
 '98.0',
 '122.0',
 '147.0',
 '148.0',
 '114.0',
 '140.0',
 '115.0',
 '101.0',
 '106.0',
 '119.0',
 '91.0',
 '112.0',
 '83.0',
 '99.0',
 '100.0',
 '87.0',
 '119.0',
 '102.0',
 '111.0',
 '94.0',
 '98.0',
 '80.0',
 '114.0',
 '81.0',
 '134.0',
 '92.0',
 '84.0',
 '135.0',
 '155.0',
 '96.0',
 '140.0',
 '102.0',
 '94.0',
 '69.0',
 '79.0',
 '69.0',
 '50.0',
 '109.0',
 '53.0',
 '80.0',
 '63.0',
 '56.0',
 '56.0',
 '82.0',
 '25.0',
 '107.0',
 '60.0',
 '61.0',
 '50.0',
 '60.0',
 '59.0',
 '81.0',
 '64.0',
 '58.0',
 '63.0',
 '44.0',
 '84.0',
 '54.0',
 '67.0',
 '58.0',
 '63.0',
 '82.0',
 '83.0',
 '83.0',
 '82.0',
 '106.0',
 '86.0',
 '120.0',
 '68.0',
 '54.0',
 '65.0',
 '82.0',
 '62.0',
 '68.0',
 '92.0',
 '68.0',
 '69.0',
 '90.0',
 '88.0',
 '94.0',
 '79.0',
 '114.0',
 '112.0',
 '158.0',
 '117.0',
 '84.0',
 '111.0',
 '83.0',
 '128.0',
 '165.0',
 '208.0',
 '192.0',
 '204.0',
 '298.0',
 '284.0',
 '289.0',
 '266.0',
 '215.0',
 '170.0',
 '176.0',
 '145.0',
 '201.0',
 '332.0',
 '399.0',
 '509.0',
 '533.0',
 '612.0',
 '581.0',
 '756.0',
 '825.0',
 '940.0',
 '908.0',
 '799.0',
 '626.0',
 '808.0',
 '469.0',
 '320.0',
 '461.0',
 '467.0',
 '557.0',
 '479.0',
 '721.0',
 '641.0',
 '826.0',
 '648.0',
 '494.0',
 '639.0',
 '466.0',
 '488.0',
 '408.0',
 '316.0',
 '448.0',
 '436.0',
 '422.0',
 '426.0',
 '431.0',
 '391.0',
 '392.0',
 '311.0',
 '302.0',
 '305.0',
 '307.0',
 '326.0',
 '291.0',
 '280.0',
 '296.0',
 '376.0',
 '274.0',
 '115.0',
 '237.0',
 '203.0',
 '75.0',
 '50.0',
 '80.0',
 '100.0',
 '167.0',
 '76.0',
 '177.0',
 '113.0',
 '161.0',
 '173.0',
 '125.0',
 '162.0',
 '182.0',
 '172.0',
 '110.0',
 '69.0',
 '86.0',
 '50.0',
 '82.0',
 '89.0',
 '70.0',
 '94.0',
 '71.0',
 '102.0',
 '121.0',
 '114.0',
 '113.0',
 '118.0',
 '209.0',
 '212.0',
 '222.0',
 '197.0',
 '275.0',
 '317.0',
 '185.0',
 '110.0',
 '90.0',
 '80.0',
 '40.0',
 '25.0',
 '25.0',
 '20.0',
 '90.0',
 '65.0',
 '44.0',
 '20.0',
 '15.0',
 '25.0',
 '20.0',
 '10.0',
 '10.0',
 '20.0',
 '10.0',
 '20.0',
 '20.0',
 '40.0',
 '45.0',
 '70.0',
 '60.0',
 '70.0',
 '65.0',
 '65.0',
 '70.0',
 '60.0',
 '90.0',
 '60.0',
 '90.0',
 '75.0',
 '95.0',
 '105.0',
 '100.0',
 '55.0',
 '60.0',
 '40.0',
 '35.0',
 '60.0',
 '85.0',
 '81.0',
 '57.0',
 '85.0',
 '87.0',
 '95.0',
 '84.0',
 '94.0',
 '77.0',
 '25.0',
 '45.0',
 '5.0',
 '25.0',
 '13.0',
 '40.0',
 '45.0',
 '40.0',
 '25.0',
 '15.0',
 '30.0',
 '30.0',
 '35.0',
 '60.0',
 '25.0',
 '40.0',
 '20.0',
 '25.0',
 '25.0',
 '15.0',
 '10.0',
 '25.0',
 '15.0',
 '20.0',
 '15.0',
 '35.0',
 '40.0',
 '2.638',
 '3.679',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '10.367',
 '9.105',
 '8.536',
 '8.058',
 '8.013',
 '6.527',
 '8.602',
 '8.059',
 '7.359',
 '7.063',
 '8.173',
 '11.66',
 '10.5',
 '7.977',
 '7.376',
 '5.508',
 '5.237',
 '5.547',
 '4.818',
 '4.758',
 '4.289',
 '4.457',
 '4.252',
 '4.814',
 '5.265',
 '4.03',
 '3.804',
 '4.331',
 '4.388',
 '4.135',
 '4.33',
 '2.975',
 '4.414',
 '5.194',
 '3.742',
 '3.743',
 '4.603',
 '4.168',
 '2.776',
 '3.278',
 '2.941',
 '4.136',
 '4.714',
 '3.864',
 '4.473',
 '4.671',
 '4.493',
 '5.754',
 '5.202',
 '4.444',
 '5.643',
 '5.076',
 '4.501',
 '4.863',
 '5.174',
 '4.963',
 '5.203',
 '5.373',
 '4.242',
 '4.868',
 '4.684',
 '3.98',
 '4.34',
 '4.296',
 '4.671',
 '4.893',
 '5.218',
 '5.255',
 '5.998',
 '6.605',
 '7.025',
 '10.148',
 '9.955',
 '8.918',
 '8.236',
 '6.305',
 '6.548',
 '7.439',
 '7.112',
 '7.993',
 '7.145',
 '7.324',
 '8.057',
 '10.494',
 '11.745',
 '9.585',
 '11.786',
 '10.887',
 '11.795',
 '12.296',
 '13.556',
 '15.102',
 '15.02',
 '19.5',
 '20.369',
 '22.312',
 '24.714',
 '20.837',
 '24.981',
 '27.391',
 '29.631',
 '30.292',
 '32.855',
 '32.495',
 '34.315',
 '37.362',
 '34.52',
 '40.113',
 '42.482',
 '37.917',
 '39.653',
 '46.346',
 '43.832',
 '46.108',
 '49.333',
 '45.231',
 '49.893',
 '49.513',
 '39.459',
 '51.404',
 '43.03',
 '27.927',
 '34.12',
 '39.478',
 '42.308',
 '43.787',
 '46.529',
 '49.752',
 '52.187',
 '48.564',
 '31.619',
 '39.06',
 '42.964',
 '29.037',
 '27.655',
 '14.482',
 '14.929',
 '17.712',
 '18.442',
 '17.717',
 '17.482',
 '15.897',
 '16.297',
 '21.616',
 '19.58',
 '16.766',
 '18.253',
 '17.198',
 '16.832',
 '17.334',
 '13.318',
 '14.032',
 '12.528',
 '15.748',
 '15.147',
 '20.877',
 '21.318',
 '22.181',
 '20.035',
 '18.35',
 '16.546',
 '17.815',
 '20.711',
 '19.709',
 '19.079',
 '20.933',
 '19.695',
 '29.167',
 '28.842',
 '24.272',
 '23.569',
 '21.791',
 ...]

#PySpark

In [284]:
# Construção do Sparksession
spark = ( 
    SparkSession.builder
                .master("local")
                .appName("dataset_derivados_pandas")
                .config("spark.ui.port", "4050")
                .getOrCreate() 
        )

In [285]:
# StructType
esquema = (
    StructType([
        
        StructField('ano_mês', DateType()),
        StructField('uf', StringType()),
        StructField('produto', StringType()),
        StructField('unid', StringType()),
        StructField('volume', DoubleType()),
        StructField('criado_em', TimestampType())
                
    ]))

In [286]:
# Ao final do arquivo csv, foi adicionado o schema do dataframe construído no StructType

dfddp = ( spark.read.format("csv")
                  .option("header", "true")
                  .option("inferschema", "true")
                  .option("delimiter", ",")
                  .load('/content/dataset_derivados_pandas.csv', schema = esquema)
)

In [287]:
# Análise dos tipos das colunas

dfddp.printSchema()

root
 |-- ano_mês: date (nullable = true)
 |-- uf: string (nullable = true)
 |-- produto: string (nullable = true)
 |-- unid: string (nullable = true)
 |-- volume: double (nullable = true)
 |-- criado_em: timestamp (nullable = true)

In [288]:
# Criando a lista de Colunas Novas

colunasNovas = []

for i in dfddp.columns:
  colunasNovas.append(i)
  print(i)

ano_mês
uf
produto
unid
volume
criado_em

In [289]:
# Verificando inconsistencias por valores unicos no topo e final das colunas

for i in range(len(colunasNovas)):
  dfddp.select(F.col(colunasNovas[i])).distinct().orderBy(colunasNovas[i], ascending=True).show(10)

+----------+
|   ano_mês|
+----------+
|2000-01-01|
|2000-02-01|
|2000-03-01|
|2000-04-01|
|2000-05-01|
|2000-06-01|
|2000-07-01|
|2000-08-01|
|2000-09-01|
|2000-10-01|
+----------+
only showing top 10 rows

+---+
| uf|
+---+
| AC|
| AL|
| AM|
| AP|
| BA|
| CE|
| DF|
| ES|
| GO|
| MA|
+---+
only showing top 10 rows

+--------------------+
|             produto|
+--------------------+
|    Etanol Hidratado|
|                 GLP|
|          Gasolina C|
| Gasolina de Aviação|
|Querosene Iluminante|
|Querosene de Aviação|
|    Óleo Combustível|
|         Óleo Diesel|
+--------------------+

+----+
|unid|
+----+
|  m3|
+----+

+------+
|volume|
+------+
|  null|
|   0.0|
|   1.0|
| 1.001|
| 1.002|
| 1.003|
| 1.004|
| 1.005|
| 1.006|
| 1.007|
+------+
only showing top 10 rows

+-------------------+
|          criado_em|
+-------------------+
|2022-09-10 00:00:00|
|2022-09-11 00:00:00|
+-------------------+

In [290]:
# Verificando inconsistencias por valores unicos no topo e final das colunas

for i in range(len(colunasNovas)):
  dfddp.select(F.col(colunasNovas[i])).distinct().orderBy(colunasNovas[i], ascending=False).show(10)

+----------+
|   ano_mês|
+----------+
|2022-12-01|
|2022-11-01|
|2022-10-01|
|2022-09-01|
|2022-08-01|
|2022-07-01|
|2022-06-01|
|2022-05-01|
|2022-04-01|
|2022-03-01|
+----------+
only showing top 10 rows

+---+
| uf|
+---+
| TO|
| SP|
| SE|
| SC|
| RS|
| RR|
| RO|
| RN|
| RJ|
| PR|
+---+
only showing top 10 rows

+--------------------+
|             produto|
+--------------------+
|         Óleo Diesel|
|    Óleo Combustível|
|Querosene de Aviação|
|Querosene Iluminante|
| Gasolina de Aviação|
|          Gasolina C|
|                 GLP|
|    Etanol Hidratado|
+--------------------+

+----+
|unid|
+----+
|  m3|
+----+

+-------+
| volume|
+-------+
|    NaN|
|  999.0|
|  998.0|
|997.923|
|997.848|
|997.237|
|  997.0|
|  996.0|
|995.166|
|  995.0|
+-------+
only showing top 10 rows

+-------------------+
|          criado_em|
+-------------------+
|2022-09-11 00:00:00|
|2022-09-10 00:00:00|
+-------------------+

In [291]:
# Tratamento de inconsistencias na coluna volume

dfddp = dfddp.replace(str('nan'), None)

In [292]:
dfddp = dfddp.replace(str('null'), None)

In [293]:
# Eliminando todos os na

dfddp=dfddp.dropna()

In [294]:
# Contagem das inconsistencias

dfddp.where(F.col('volume').isNull()).count()

0

In [295]:
dfddp.show()

+----------+---+----------------+----+------+-------------------+
|   ano_mês| uf|         produto|unid|volume|          criado_em|
+----------+---+----------------+----+------+-------------------+
|2000-01-01| AC|Etanol Hidratado|  m3| 501.0|2022-09-10 00:00:00|
|2000-02-01| AC|Etanol Hidratado|  m3| 454.0|2022-09-10 00:00:00|
|2000-03-01| AC|Etanol Hidratado|  m3| 676.0|2022-09-10 00:00:00|
|2000-04-01| AC|Etanol Hidratado|  m3| 678.0|2022-09-10 00:00:00|
|2000-05-01| AC|Etanol Hidratado|  m3| 1.467|2022-09-10 00:00:00|
|2000-06-01| AC|Etanol Hidratado|  m3| 351.0|2022-09-10 00:00:00|
|2000-07-01| AC|Etanol Hidratado|  m3| 451.0|2022-09-10 00:00:00|
|2000-08-01| AC|Etanol Hidratado|  m3| 603.0|2022-09-10 00:00:00|
|2000-09-01| AC|Etanol Hidratado|  m3| 531.0|2022-09-10 00:00:00|
|2000-10-01| AC|Etanol Hidratado|  m3| 573.0|2022-09-10 00:00:00|
|2000-11-01| AC|Etanol Hidratado|  m3| 305.0|2022-09-10 00:00:00|
|2000-12-01| AC|Etanol Hidratado|  m3| 566.0|2022-09-10 00:00:00|
|2001-01-01| AC|Etanol Hidratado|  m3| 431.0|2022-09-10 00:00:00|
|2001-02-01| AC|Etanol Hidratado|  m3| 387.0|2022-09-10 00:00:00|
|2001-03-01| AC|Etanol Hidratado|  m3| 428.0|2022-09-10 00:00:00|
|2001-04-01| AC|Etanol Hidratado|  m3| 401.0|2022-09-10 00:00:00|
|2001-05-01| AC|Etanol Hidratado|  m3| 427.0|2022-09-10 00:00:00|
|2001-06-01| AC|Etanol Hidratado|  m3| 446.0|2022-09-10 00:00:00|
|2001-07-01| AC|Etanol Hidratado|  m3| 402.0|2022-09-10 00:00:00|
|2001-08-01| AC|Etanol Hidratado|  m3| 476.0|2022-09-10 00:00:00|
+----------+---+----------------+----+------+-------------------+
only showing top 20 rows

In [296]:
dfddp.dtypes

[('ano_mês', 'date'),
 ('uf', 'string'),
 ('produto', 'string'),
 ('unid', 'string'),
 ('volume', 'double'),
 ('criado_em', 'timestamp')]

In [297]:
# Salvar o dataset em 
dfddp.write.csv('dataset_derivados_anp.csv')

# Tratamento do Dataset referente ao Diesel

In [ ]:
# Carregamento do Dataframe Localmente

dfdieselpandas = pd.read_csv('/content/dataset_oleo_diesel.csv',sep=',')

In [ ]:
# Análise dos dados da coluna volume

listavolumed = []

for i in dfdieselpandas['volume']:
  listavolumed.append(i)

In [ ]:
listavolumed

In [ ]:
# Construção do Sparksession
spark = ( 
    SparkSession.builder
                .master("local")
                .appName("dataset_diesel_pandas")
                .config("spark.ui.port", "4050")
                .getOrCreate() 
        )

In [ ]:
# StructType
esquema = (
    StructType([
        
        StructField('ano_mês', DateType()),
        StructField('uf', StringType()),
        StructField('produto', StringType()),
        StructField('unid', StringType()),
        StructField('volume', DoubleType()),
        StructField('criado_em', TimestampType())
                
    ]))

In [ ]:
# Ao final do arquivo csv, foi adicionado o schema do dataframe construído no StructType

dfdiesel = ( spark.read.format("csv")
                  .option("header", "true")
                  .option("inferschema", "true")
                  .option("delimiter", ",")
                  .load('/content/dataset_oleo_diesel.csv', schema = esquema)
)

In [ ]:
# Análise dos tipos das colunas

dfdiesel.printSchema()

In [ ]:
# Criando a lista de Colunas Novas

colunasNovas = []

for i in dfdiesel.columns:
  colunasNovas.append(i)
  print(i)

ano_mês
uf
produto
unid
volume
criado_em

In [ ]:
# Verificando inconsistencias por valores unicos no topo e final das colunas

for i in range(len(colunasNovas)):
  dfdiesel.select(F.col(colunasNovas[i])).distinct().orderBy(colunasNovas[i], ascending=True).show(10)

In [ ]:
# Verificando inconsistencias por valores unicos no topo e final das colunas

for i in range(len(colunasNovas)):
  dfdiesel.select(F.col(colunasNovas[i])).distinct().orderBy(colunasNovas[i], ascending=False).show(10)

+----------+
|   ano_mês|
+----------+
|2022-12-01|
|2022-11-01|
|2022-10-01|
|2022-09-01|
|2022-08-01|
|2022-07-01|
|2022-06-01|
|2022-05-01|
|2022-04-01|
|2022-03-01|
+----------+
only showing top 10 rows

+---+
| uf|
+---+
| TO|
| SP|
| SE|
| SC|
| RS|
| RR|
| RO|
| RN|
| RJ|
| PR|
+---+
only showing top 10 rows

+-----------+
|    produto|
+-----------+
|Óleo Diesel|
+-----------+

+----+
|unid|
+----+
|  m3|
+----+

+-------+
| volume|
+-------+
|997.923|
|997.848|
|997.237|
|992.246|
|989.328|
|986.825|
|985.268|
| 982.66|
| 982.12|
|977.727|
+-------+
only showing top 10 rows

+-------------------+
|          criado_em|
+-------------------+
|2022-09-11 00:00:00|
+-------------------+

In [ ]:
# Contagem das inconsistencias

dfdiesel.where(F.col('volume').isNull()).count()

0

In [ ]:
# Tratamento de inconsistencias na coluna volume

dfdiesel = dfdiesel.replace(str('nan'), None)

In [ ]:
dfdiesel = dfdiesel.replace(str('null'), None)

In [ ]:
# Eliminando todos os na

dfdiesel=dfdiesel.dropna()

In [ ]:
dfdiesel.show()

+----------+---+-----------+----+------+-------------------+
|   ano_mês| uf|    produto|unid|volume|          criado_em|
+----------+---+-----------+----+------+-------------------+
|2000-01-01| AC|Óleo Diesel|  m3|18.025|2022-09-11 00:00:00|
|2000-02-01| AC|Óleo Diesel|  m3|18.336|2022-09-11 00:00:00|
|2000-03-01| AC|Óleo Diesel|  m3|16.654|2022-09-11 00:00:00|
|2000-04-01| AC|Óleo Diesel|  m3|15.146|2022-09-11 00:00:00|
|2000-05-01| AC|Óleo Diesel|  m3|18.681|2022-09-11 00:00:00|
|2000-06-01| AC|Óleo Diesel|  m3|17.949|2022-09-11 00:00:00|
|2000-07-01| AC|Óleo Diesel|  m3|17.466|2022-09-11 00:00:00|
|2000-08-01| AC|Óleo Diesel|  m3|19.174|2022-09-11 00:00:00|
|2000-09-01| AC|Óleo Diesel|  m3|19.505|2022-09-11 00:00:00|
|2000-10-01| AC|Óleo Diesel|  m3| 19.96|2022-09-11 00:00:00|
|2000-11-01| AC|Óleo Diesel|  m3|19.349|2022-09-11 00:00:00|
|2000-12-01| AC|Óleo Diesel|  m3|18.796|2022-09-11 00:00:00|
|2001-01-01| AC|Óleo Diesel|  m3|20.061|2022-09-11 00:00:00|
|2001-02-01| AC|Óleo Diesel|  m3|16.449|2022-09-11 00:00:00|
|2001-03-01| AC|Óleo Diesel|  m3|20.859|2022-09-11 00:00:00|
|2001-04-01| AC|Óleo Diesel|  m3|17.388|2022-09-11 00:00:00|
|2001-05-01| AC|Óleo Diesel|  m3|20.052|2022-09-11 00:00:00|
|2001-06-01| AC|Óleo Diesel|  m3|18.046|2022-09-11 00:00:00|
|2001-07-01| AC|Óleo Diesel|  m3|19.756|2022-09-11 00:00:00|
|2001-08-01| AC|Óleo Diesel|  m3|21.717|2022-09-11 00:00:00|
+----------+---+-----------+----+------+-------------------+
only showing top 20 rows

In [ ]:
# Salvando arquivo em csv

dfdiesel.write.csv('diesel.csv')